module.exports = grammar({
  name: "bat",

  extras: ($) => [/\s/, $.comment],

  word: ($) => $.identifier,

  rules: {
    source_file: ($) => repeat($._statement),

    shebang: ($) => seq("#!", /.*/),

    comment: ($) => token(seq(choice("REM", "rem", "Rem"), /.*/)),

    _statement: ($) => choice($.command, $.label),

    // Label definition (e.g., :label_name)
    label: ($) =>
      prec.right(seq(":", field("name", $.identifier), optional(/\r?\n/))),

    // General command - handles all batch commands
    command: ($) =>
      prec.right(
        seq(
          field("name", $.command_name),
          repeat(field("argument", $._argument)),
          optional(/\r?\n/),
        ),
      ),

    command_name: ($) =>
      choice(
        // Built-in commands
        "ECHO",
        "echo",
        "Echo",
        "SET",
        "set",
        "Set",
        "IF",
        "if",
        "If",
        "FOR",
        "for",
        "For",
        "GOTO",
        "goto",
        "Goto",
        "CALL",
        "call",
        "Call",
        "EXIT",
        "exit",
        "Exit",
        "PAUSE",
        "pause",
        "Pause",
        "CLS",
        "cls",
        "Cls",
        "CD",
        "cd",
        "Cd",
        "CHDIR",
        "chdir",
        "Chdir",
        "COPY",
        "copy",
        "Copy",
        "DEL",
        "del",
        "Del",
        "ERASE",
        "erase",
        "Erase",
        "DIR",
        "dir",
        "Dir",
        "MKDIR",
        "mkdir",
        "Mkdir",
        "MD",
        "md",
        "Md",
        "RMDIR",
        "rmdir",
        "Rmdir",
        "RD",
        "rd",
        "Rd",
        "RENAME",
        "rename",
        "Rename",
        "REN",
        "ren",
        "Ren",
        "TYPE",
        "type",
        "Type",
        "FIND",
        "find",
        "Find",
        "FINDSTR",
        "findstr",
        "Findstr",
        "attrib",
        "break",
        "color",
        "comp",
        "compact",
        "convert",
        "date",
        "time",
        "driverquery",
        "endlocal",
        "fc",
        "ftype",
        "getmac",
        "gpresult",
        "help",
        "hostname",
        "ipconfig",
        "label",
        "logman",
        "mapadmin",
        "mklink",
        "mode",
        "more",
        "move",
        "msg",
        "net",
        "netsh",
        "nslookup",
        "openfiles",
        "pathping",
        "ping",
        "popd",
        "print",
        "prompt",
        "pushd",
        "query",
        "rasdial",
        "recover",
        "reg",
        "replace",
        "route",
        "runas",
        "schtasks",
        "setlocal",
        "shift",
        "shutdown",
        "sort",
        "start",
        "subst",
        "systeminfo",
        "taskkill",
        "tasklist",
        "timeout",
        "title",
        "tracert",
        "tree",
        "ver",
        "verify",
        "vol",
        "vssadmin",
        "where",
        "whoami",
        "wmic",
        // Generic identifier as command
        $.identifier,
      ),

    _argument: ($) =>
      choice(
        $.string,
        $.variable,
        $.number,
        $.redirect_operator,
        $.pipe_operator,
        $.flag,
        $.path,
        $.identifier,
      ),

    string: ($) => choice(seq('"', /[^"]*/, '"'), seq("'", /[^']*/, "'")),

    number: ($) => /\d+/,

    path: ($) => /[%~]?[A-Za-z]:\\[^\s"']*/,

    flag: ($) => prec.left(seq("/", /[A-Za-z0-9]+/)),

    identifier: ($) => /[A-Za-z_][A-Za-z0-9_\-]*/,

    // Variables
    variable: ($) =>
      choice(
        $.special_variable,
        $.parameter_variable,
        $.environment_variable,
        $.substring_variable,
        $.for_variable,
      ),

    special_variable: ($) =>
      seq(
        "%",
        choice(
          "0",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "*",
          "@",
          "DATE",
          "TIME",
          "CD",
          "PATH",
          "RANDOM",
          "ERRORLEVEL",
          "CMDEXTVERSION",
          "CMDCMDLINE",
          "HIGHESTNUMANODENUMBER",
          "PROCESSOR_ARCHITECTURE",
          "PROCESSOR_LEVEL",
          "PROCESSOR_REVISION",
          "NUMBER_OF_PROCESSORS",
          "OS",
          "USERNAME",
          "USERDOMAIN",
          "COMPUTERNAME",
          "HOMEDRIVE",
          "HOMEPATH",
          "TEMP",
          "TMP",
          "SYSTEMROOT",
          "WINDIR",
          "PROGRAMFILES",
          "PROGRAMFILES(X86)",
        ),
        "%",
      ),

    parameter_variable: ($) => seq("%", /[0-9*]/, "%"),

    environment_variable: ($) => seq("%", $.identifier, "%"),

    substring_variable: ($) =>
      seq(
        "%",
        $.identifier,
        ":",
        optional(/~?[0-9\-]+/),
        optional(":"),
        optional(/~?[0-9\-]+/),
        "%",
      ),

    for_variable: ($) => seq("%%", $.identifier),

    // Redirect operators
    redirect_operator: ($) =>
      choice(">", ">>", "<", ">&1", "2>", "2>>", "1>", "1>>", "0<"),

    // Pipe operator
    pipe_operator: ($) => "|",
  },
});
